spring.application.name=MajorBeat-API

spring.datasource.url=jdbc:sqlserver://server-majorbeat.database.windows.net:1433;databaseName=MajorBeatDB2;encrypt=true;trustServerCertificate=false;loginTimeout=30;
spring.datasource.username=sa-major-beat
spring.datasource.password=*123456HAS*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#Blob Storage
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=majorbeatcloud;AccountKey=ZiMqVZ2O3Uri8l+kJUL1g0oo1Oq2tmhsz2EHgSScPZ/ZZCvgHI/nwAyh/XGtHa9PBQYp6SjnqXdN+AStukY5rA==;EndpointSuffix=core.windows.net
azure.storage.container-name=arquivos
azure.storage.account-name=majorbeatcloud
azure.storage.account-key=ZiMqVZ2O3Uri8l+kJUL1g0oo1Oq2tmhsz2EHgSScPZ/ZZCvgHI/nwAyh/XGtHa9PBQYp6SjnqXdN+AStukY5rA==
